### ISSUE TITLE
How to mock @magic-sdk/admin in NodeJS or enable Test Mode in Magic Admin SDK?

### ISSUE THREAD

**Issue by jesuslopezlugo** [magiclabs/magic-admin-js#103]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [X] Are you reporting to the correct repository (`@magic-sdk/admin`)?

### ❓ Question

How to mock @magic-sdk/admin in NodeJS or enable Test Mode in Magic Admin SDK?

I'm trying to mock `@magic-sdk/admin` using [sinon.js](https://sinonjs.org/) without success. 

Do you have test mode for admin sdk like [you have for client sdk](https://magic.link/docs/auth/introduction/test-mode)?

In order to create valid test did token and make unit testing with my code

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` | 1.8.0
| Node               | 16.19.0
| `npm`             | 8.19.3
| Operating System   | Mac OS

**Comment by ayv8er** [comment]
@jesuslopezlugo 
We don't have a testMode configuration available for the admin SDK.
The token resolved from a client SDK configured to testMode will have limited abilities in the admin SDK.
You can see the expected behaviors in our docs to guide you.
https://magic.link/docs/auth/introduction/test-mode#expected-behavior
