### ISSUE TITLE
getMetadataByTokenAndWallet always returns empty

### ISSUE THREAD

**Issue by wiredmatt** [magiclabs/magic-admin-js#128]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`@magic-sdk/admin`)?

### 🐛 Description

Using the SDK's `getMetadataByTokenAndWallet` will always return an empty array of wallets. The API request through a plain curl call works as expected though.

```typescript
magic.token.validate(token); // returns void if valid, throws if not
req.magicUser = await magic.users.getMetadataByTokenAndWallet(
  token,
  "SUI" as any // use whatever here, wallets response will always be empty.
);
```

What the SDK returns:
![image](https://github.com/magiclabs/magic-admin-js/assets/29718978/fc004fc9-e596-4d94-aed1-951f974b259a)

What the API returns:

```
curl --request GET \
  --url 'https://api.magic.link/v1/admin/auth/user/get?issuer=did%3Aethr%3A0x2B05D3f84BeEE532A0FD92B07586EfB141C78d6B&wallet_type=SUI' \
  --header 'X-Magic-Secret-key: sk_live_changeme'
```
![image](https://github.com/magiclabs/magic-admin-js/assets/29718978/27cf819c-457a-420b-aca8-ccf37e18761d)

```json
{
  "data": {
    "email": "some@gmail.com",
    "issuer": "did:ethr:0x2B05D3f84BeEE532A0FD92B07586EfB141C78d6B",
    "oauth_provider": null,
    "phone_number": null,
    "public_address": "0x2B05D3f84BeEE532A0FD92B07586EfB141C78d6B",
    "wallets": [
      {
        "network": "MAINNET",
        "public_address": "0xa5d2e18eec61c5a2224e5512ca1cb5ba16c0749d1cfe3fc6c52264b887bfaf76",
        "wallet_type": "SUI"
      }
    ]
  },
  "error_code": "",
  "message": "",
  "status": "ok"
}
```

[Description of the bug.]

### 🧩 Steps to Reproduce

1. run `magic.users.getMetadataByTokenAndWallet` in a nodejs application.

### 🤔 Expected behavior

It should return what the HTTP API does.

### 😮 Actual behavior

It didn't return what the HTTP API does.

### 💻 Code Sample

```typescript
magic.token.validate(token); // returns void if valid, throws if not
req.magicUser = await magic.users.getMetadataByTokenAndWallet(
  token,
  "SUI" as any // use whatever here, wallets response will always be empty.
);
```

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` |
| Node               |
| `yarn`             |
| Operating System   |

**Comment by ayv8er** [comment]
@wiredmatt 
What is the NodeJS SDK version you're on?

**Comment by wiredmatt** [comment]
Hey Richard! This is very very old and I'm not working on that project any longer. May as well close this issue.
We fixed it by making raw http calls to the API.
