### ISSUE TITLE
Encode url

### ISSUE THREAD

**Issue by FYJen** [magiclabs/magic-admin-js#21]
Admin sdk should encode the url to prevent non-conforming characters:
```
https://api.magic.link/v1/admin/auth/user/get?issuer=did:ethr:0xA093F00c775c0b7DF6E15355B039A9336A7Ff81E
```

The whole url should be encoded or the query parameter should be `did:ethr:0xA093F00c775c0b7DF6E15355B039A9336A7Ff81E`. The `:` has specific meaning in the url when it follows after the domain to specify the port number. I don't think it has any effect in the query string.

It is a good practice to encode the url particularly the one with special characters.

**Comment by smithki** [comment]
:rocket: Issue was released in [`v1.3.0`](https://github.com/magiclabs/magic-admin-js/releases/tag/v1.3.0) :rocket:
