### ISSUE TITLE
Add NodeJS Examples

### ISSUE THREAD

**Issue by sheksushant** [magiclabs/magic-admin-js#52]
What's the point of logging out if our users can't login? https://docs.magic.link/admin-sdk/node/examples/log-out-a-users-magic-session

Hope Login/SignUp Examples will be added soon.

**Comment by miguel-a-calles-mba** [comment]
This issue might be addressed. https://magic.link/docs/api-reference/server-side-sdks/node

**Comment by am-hernandez** [comment]
Hi @sheksushant , thank you for the question. I understand it is long overdue, but I wanted to close this issue with an answer. 
Users log in via the client-side SDKs and not the server-side SDKs (Admin SDK). The Magic Admin SDK does provide the ability to log a user out of all sessions, which is very useful for security reasons. Logins occur client-side using Magic's iframe to provide a secure connection for the user and AWS. You can dive deeper into the auth flow by checking out our [security docs](https://magic.link/docs/home/security).
