### ISSUE TITLE
Facing issue while setting custom cookies from serverless backend

### ISSUE THREAD

**Issue by hmble** [magiclabs/magic-admin-js#66]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? 
- [ ] Is this bug already reported elsewhere? ( Could not find any reference related to this issue as per my understanding )
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`@magic-sdk/admin`)?

### 🐛 Description
Hello, I am using admin sdk for verfying `didToken` which is passed by api call in the callback url.
Once the `didToken` is verified from magic server I am trying to set my own manual cookie in browser. When I checked the application tab in the chrome developer tools cookies section, I am unable to see the cookie set over there.

The stack that I am using :
1. Nextjs ( frontend)
2. AWS lambda ( backend )
3. AWS API Gateway ( reverse proxy )
4. Serverless Framework ( Iaas)

In my observation when I commented the code 
```js
const didToken = event.headers.Authorization.substring(7);
magic.token.validate(didToken);
const issuer = magic.token.getIssuer(didToken);
```

The cookies gets successfully set from lambda to nextjs application.

Heres how I am trying to set cookie in the browser from my serverless backend
```js
const cookie = serialize("qidts", key, {
      httpOnly: true,
      maxAge: 60 * 60 * 24 * 7, // 1 week
      sameSite: "none",
      // domain: ".amazonaws.com",
      secure: false,
      // path: "/",
    });
    return {
      statusCode: status,
      headers: {
        "Set-Cookie": cookie,
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Credentials": true,
      },
      body: JSON.stringify(response),
    };
```

NOTE: I am running api gateway and aws lambda on my machine using serverless framework `serverless-offline` plugin
[Description of the bug.]

### 🧩 Steps to Reproduce

1. Created the frontend nextjs application [example](https://github.com/vercel/next.js/tree/canary/examples/with-magic)
2. I removed the nextjs api route code in the example and moved it to aws lambda backend.

### 🤔 Expected behavior

It should set cookie in browser

### 😮 Actual behavior

Not setting cookies in browser. Also not setting cookies provided by magic link.

I am also seeing following errors in developer tool. i dont know if it would be helpful.

![Screenshot_20210917_185911](https://user-images.githubusercontent.com/16825207/133793322-8907c600-660b-4a94-b5e5-6bdc4cec9f47.png)

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` | ^1.3.0
| Node               | v14.17.4
| `npm`             |6.14.11
| Operating System   | Linux

**Comment by smithki** [comment]
> Hello, I am using admin sdk for verfying didToken which is passed by api call in the callback url.
Once the didToken is verified from magic server I am trying to set my own manual cookie in browser.

Just to make sure I am understanding you correctly: you have successfully passed a DID token to your backend and verified it using the Magic JS Admin SDK?

---

The developer tools errors you're seeing related to `magic.link` cookies are expected as those are **cross-site, client-side cookies** that are used by our logging tools to aid in troubleshooting issues with our code. Those would be unrelated to your cookie, which is controlled by your server under your own domain. For this, I would encourage you to [ask a question on StackOverflow](https://stackoverflow.com/questions/ask), where you'll be able to get more specialized support for HTTP/cookie-related obstacles.

---

As this is unrelated to the behavior of Magic JS Admin SDK itself, I'm going to close it, but please feel free to respond with additional context if you feel I am missing something.
