### ISSUE TITLE
When can we expect phone_number to be available in admin-sdk for Typescript?

### ISSUE THREAD

**Issue by ihpannu** [magiclabs/magic-admin-js#73]

**Comment by smithki** [comment]
We have some internal resources planned to tackle this soon (next 2 weeks), but open to a PR if you want to see it land even sooner. Two code changes would be required:

- Add `phoneNumber: string | null` to the `MagicUserMetadata` interface [here](https://github.com/magiclabs/magic-admin-js/blob/d94f52310ea1e5a533586b9a001e37d4d6d18601/src/types/sdk-types.ts#L5)
- Add `phoneNumber` to the response given by the `getMetadataByIssuer` method [here](https://github.com/magiclabs/magic-admin-js/blob/d94f52310ea1e5a533586b9a001e37d4d6d18601/src/modules/users/index.ts#L38)
- Update tests [here](https://github.com/magiclabs/magic-admin-js/blob/master/test/spec/modules/users/getMetadataByIssuer.spec.ts)

**Comment by justinnout** [comment]
Phone number already supported in latest version. Closing for now unless!
