### ISSUE TITLE
getPublicAddress will always return the ETH public key

### ISSUE THREAD

**Issue by bmeeder22** [magiclabs/magic-admin-js#78]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`@magic-sdk/admin`)?

### 🐛 Description

When attempting to verify a user is who they say that they are, we need to be able to verify that they're public keys are the same. If a token is generated for example with the `SolanaExtension` enabled we should be able to get the public address of the user for the `solana` blockchain. Right now the only available option is ETH. This applies to `decode` as well as `getMetadataByPublicAddress`. 

### 🧩 Steps to Reproduce

1. Generate a Did token using magic-js with SolanaExtension.
2. Pass that to magic-admin and call `magic.token.getPublicAddress(DidToken)`
3. See that the address is a ETH address (starts with 0x)

### 🤔 Expected behavior

`getPublicAddress` should return the users associated Solana Wallet Public Key

### 😮 Actual behavior

Returns the users ETH public key

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` | `1.3.4`
| Node               | `16.7`
| Operating System   | `any`

**Comment by bmeeder22** [comment]
@harryEth Any updates on this?

**Comment by ayv8er** [comment]
@bmeeder22 This isn't a bug report, but it is a valid feature request. I'll be putting this under the attention of our Product team so we can add it to our roadmap.
