### ISSUE TITLE
Malformed Token on deployment

### ISSUE THREAD

**Issue by heymartinadams** [magiclabs/magic-admin-js#86]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`@magic-sdk/admin`)?

### 🐛 Description

Using `localhost` I’m able to log in without a hitch. But as soon as I deploy (in my case, to Vercel), even while remaining in `development` environment, I run into the following error — **but only for `@magic-sdk/admin` version `1.4.0`. This bug does not appear for `1.3.4`**:

```
ERROR	MagicAdminSDKError: Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] The DID token is malformed or failed to parse.
    at new MagicAdminSDKError (/var/task/node_modules/@magic-sdk/admin/dist/cjs/core/sdk-exceptions.js:22:28)
    at Object.createMalformedTokenError (/var/task/node_modules/@magic-sdk/admin/dist/cjs/core/sdk-exceptions.js:54:12)
    at Object.parseDIDToken (/var/task/node_modules/@magic-sdk/admin/dist/cjs/utils/parse-didt.js:33:32)
    at TokenModule.decode (/var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/token/index.js:86:40)
    at TokenModule.getIssuer (/var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/token/index.js:95:21)
    at UsersModule.<anonymous> (/var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/users/index.js:137:41)
    at step (/var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/users/index.js:46:23)
    at Object.next (/var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/users/index.js:27:53)
    at /var/task/node_modules/@magic-sdk/admin/dist/cjs/modules/users/index.js:21:71
    at new Promise (<anonymous>) {
  code: 'ERROR_MALFORMED_TOKEN',
  data: []
}
```

It looks like there’s a discussion over at NextJS (which I also use): https://github.com/vercel/next.js/discussions/21394

No idea why it’s not working. I use Magic on two other projects, and they’re working fine.

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` | `1.4.0`
| Node               | `17.4.0`
| `yarn`             | `1.22.18`
| Operating System   | `macOS 12.2.1`

**Comment by RobSchilderr** [comment]
Which nextjs version are you using @heymartinadams ?

**Comment by heymartinadams** [comment]
Indeed, using `12.1.4`! Will test earlier versions and update this comment once I have...

**Comment by heymartinadams** [comment]
@RobSchilderr @Edjevw12 The issue seems not to be with `next` but with `@magic-sdk/admin`, specifically version `1.4.0`. I downgraded `next` all the way to `12.0.0` and it didn’t resolve the issue, but as soon as I downgraded `@magic-sdk/admin` to `1.3.4` I was able to log in on the deployment build.

**Comment by RobSchilderr** [comment]
> Indeed, using `12.1.4`! Will test earlier versions and update this comment once I have... @RobSchilderr @Edjevw12 The issue seems not to be with `next` but with `@magic-sdk/admin`, specifically version `1.4.0`. I downgraded `next` all the way to `12.0.0` and it didn’t resolve the issue, but as soon as I downgraded `@magic-sdk/admin` to `1.3.4` I was able to log in on the deployment build.

You are right. It does work at `@magic-sdk/admin` in version`1.3.4`. So to the maintainers of this package: I had this exact same issue but my `@magic-sdk/admin` version was `1.0.0` and my `next` version was at `12.0.7` and also at `12.1.2`.

**Comment by herbievine** [comment]
I've got the Admin SDK running in a Nest.js server (not Next), and am still getting the error...

I have an auth service which handles all of the magic stuff...

```typescript
@Injectable()
export class AuthService {
  constructor(private readonly usersService: UsersService) {}

  public async login(
    payload: CreateOrLoginUserDto,
    didToken: string
  ): Promise<AuthenticatedUser> {
    console.log(magic().secretApiKey) // sk_live_xxxxx

    const s = magic().token.validate(didToken) 
    // Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] The DID token is malformed or failed to parse.

    console.log(s)

    const user = await this.usersService.createOrLoginUser({
      ...payload,
      didToken
    })

    return {
      jwt: 'string',
      user
    }
  }
}
```

**Comment by magalidefelippe** [comment]
I have the same error running in local :( nextjs and typescript!

**Comment by magalidefelippe** [comment]
I downgraded the magic version to 1.3.4 and finally works in local ----> Maybe possible solution!

**Comment by abhijeetd700** [comment]
Hey even if I downgraded the magic link admin SDK to v 1.3.4 not able to login in to the server on the production . Locally everything is working fine .......
The main issue which I am facing that the DID token generated is not vaildated in the back end (Node js v 12.18.0) .

Error code at validation line number 328 [](https://imgur.com/tNAIWZJ)

AWS Server log error [](https://imgur.com/N3SixsG)

**Comment by VladimirMikulic** [comment]
**This is not an issue with Magic's SDK.**

**Some Vercel regions** don't provide the correct runtime for serverless functions.
https://vercel.com/docs/concepts/functions/edge-functions#runtime-apis

[globalThis/global object](https://github.com/magiclabs/magic-admin-js/blob/7202159938ba2f77dc6c7c7ee6fa7f36a03518a4/src/utils/parse-didt.ts#L13) is supposed to have `atob`/`btoa` functions.

We run native Node.js runtime locally so Magic logins work, but as soon as you deploy these functions are no longer provided on Vercel's custom Node.js runtime. That's why it breaks.

Until Vercel fixes their runtime, we can polyfill it. (`yarn add atob`)
```js
import atob from `atob`

// Somewhere before Magic Admin
globalThis.atob = atob;
```

Now enjoy your weekend!

https://github.com/vercel/next.js/issues/36030

**Comment by magalidefelippe** [comment]
Thank you so much @VladimirMikulic 👯

**Comment by VladimirMikulic** [comment]
Glad I could help!

**Comment by VladimirMikulic** [comment]
That's the case for Vercel as well. (runs on Node.js 14)
Maybe it would make sense for Magic to add `engines` field in package.json so we get a warning when version < Node.js 16 or polyfill `atob` themselves.

**Comment by herbievine** [comment]
> I've got the Admin SDK running in a Nest.js server (not Next), and am still getting the error...
> 
> I have an auth service which handles all of the magic stuff...
> 
> ```ts
> @Injectable()
> export class AuthService {
>   constructor(private readonly usersService: UsersService) {}
> 
>   public async login(
>     payload: CreateOrLoginUserDto,
>     didToken: string
>   ): Promise<AuthenticatedUser> {
>     console.log(magic().secretApiKey) // sk_live_xxxxx
> 
>     const s = magic().token.validate(didToken) 
>     // Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] The DID token is malformed or failed to parse.
> 
>     console.log(s)
> 
>     const user = await this.usersService.createOrLoginUser({
>       ...payload,
>       didToken
>     })
> 
>     return {
>       jwt: 'string',
>       user
>     }
>   }
> }
> ```

Does anyone have an idea for my issue?

**Comment by VladimirMikulic** [comment]
@herbievine just polyfill `atob` on `globalThis`.

**Comment by kushqbs-1234** [comment]
#for nest js
var atob = require('atob');
globalThis.atob = atob;

**Comment by Ethella** [comment]
Sorry for the late reply. Taking a look at this now

**Comment by Ethella** [comment]
I just synced with the team, we don't have any updates recently in the admin-SDK. 

Shout out to @VladimirMikulic. Please refer to his answer if you have run into the same issue. 
https://github.com/magiclabs/magic-admin-js/issues/86#issuecomment-1093728064

Feel free to re-open the ticket if anyone has encountered subsequent issue

**Comment by VladimirMikulic** [comment]
Thanks, @Ethella.
It would be helpful if you could add `engines` file to package.json so people get warned immediately that they are using wrong Node.js version.

```json
"engines": {
  "node": "16.x"
},
```

This line requires Node.js v16 since `atob` is not available on previous Node.js versions.
https://github.com/magiclabs/magic-admin-js/blob/master/src/utils/parse-didt.ts#L15
(updated on Feb 17, the previous revision relied on `Buffer` which is, as far as I know, available in all Node.js versions)

**Comment by Ethella** [comment]
@VladimirMikulic As this error is Vercel specifically, I think adding `engines` to package.json will narrow down other use cases with Node.js. Potentially, I can add a polyfill of `atob` to the SDK, in case the node environment does not provide one. That'll resolve the issue for everyone else.

**Comment by VladimirMikulic** [comment]
@Ethella sorry, perhaps my original explanation wasn't clear enough.
Although Vercel does run custom Node.js 14 runtime, magic-sdk wouldn't work on native Node.js 14 runtime either.

That's because Node.js introduced `atob` in version 16. Previous Node.js versions don't have it.
https://developer.mozilla.org/en-US/docs/Web/API/atob

This warning would be universal (i.e. dev installing magic-sdk while running Node.js 14), not limited to Vercel.
It would prevent devs discovering this issue at runtime.

**Comment by Ethella** [comment]
> 🚀 PR was released in [`v1.4.1`](https://github.com/magiclabs/magic-admin-js/releases/tag/v1.4.1) 🚀

**Comment by heymartinadams** [comment]
Thank you, @Ethella!

**Comment by wandriputra** [comment]
I have this issue when user login with their phone number sometimes.
