### ISSUE TITLE
Module is not being installed properly

### ISSUE THREAD

**Issue by nbusser** [magiclabs/magic-admin-js#97]
### 🐛 Description

When installed with npm or yarn, `@magic-sdk/admin` shows an empty `dist`
When installing `@magic-sdk/admin` either with `npm` or `yarn`, the content of installed package seems empty.

#### Using yarn

1. Go to an empty repository
2. Run `yarn add @magic-sdk/admin`
3. Run `ls -al node_modules/@magic-sdk/admin`

#### Using npm

1. Go to an empty repository
2. Run `npm install @magic-sdk/admin`
3. Run `ls -al node_modules/@magic-sdk/admin`

### 🤔 Expected behavior

A `dist` folder, containing the javascript code is supposed to be present

### 😮 Actual behavior

Here is the content of the installed module:

#### Using yarn

![image](https://user-images.githubusercontent.com/25375465/203307500-07cd552b-a07d-4be5-983f-0db25472e9e1.png)

#### Using npm

![image](https://user-images.githubusercontent.com/25375465/203309297-772dee1d-9b7f-4926-a206-2c07c5f1223b.png)

### 🌎 Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| `@magic-sdk/admin` | 1.5.0
| Node               |  16.10.0 (also tried in 14.15.0)
| `yarn`             | 1.22.19
| `npm`             | 7.24.0
| Operating System   | Mac OS

**Comment by justinnout** [comment]
Hi @nbusser, apologies for this! There is an issue with our npm publishing pipeline. We are working on a fix.
